services:
  wwtb-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: wwtb-client
    # ports:
    #   - "3005:3000"
    expose:
      - "3000"
    restart: always
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=wewantthemback.berlin,www.wewantthemback.berlin   # Nginx Proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=wewantthemback.berlin,www.wewantthemback.berlin   # SSL Domain
      - LETSENCRYPT_EMAIL=dain-p@visual-intelligence.org # SSL Email

    networks:
      - shared_network
    
networks:
  shared_network: