services:
  wwtb-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: wwtb-client
    ports:
      - "3005:3000"
    restart: always
    env_file:
      - .env.production

    # test
    networks:
      - shared_network
    
networks:
  shared_network: